name: HEP_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=1.26
  - pandas>=2.2
  - uproot>=5.3
  - awkward>=2.6
  - vector>=1.3
  - hist>=2.7
  - matplotlib>=3.8
  - dask>=2024.0.0
  - jupyterlab>=4.2
  - ipywidgets>=8.1
  - tqdm>=4.66
  - psutil>=5.9
  - scipy>=1.13
  - pip
  - pip:
    - coffea>=0.7
    - fsspec-xrootd>=0.2
    - prettytable>=3.10
